# Versión de la sintaxis de Docker Compose
version: "3.8"

# Definición de los servicios (contenedores)
services:
  # Servicio de la base de datos
  db:
    image: mariadb:latest
    container_name: mariadb-clarisa
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: referidos_clarisa_cloud
    ports:
      - "3306:3306"
    volumes:
      - mariadb_datos:/var/lib/mysql

  # Servicio de caché con Redis
  # cache:
  #   image: redis:alpine
  #   container_name: redis-clarisa
  #   restart: unless-stopped

  # Servicio de la aplicación Node.js
  app:
    # Construye la imagen a partir del Dockerfile en el directorio actual
    build: .
    container_name: sirc-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      # La aplicación no se iniciará hasta que la DB y el caché estén listos
      - db
    #      - cache
    environment:
      # Usa los nombres de los servicios para la conexión
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: referidos_clarisa_cloud
      #CACHE_DRIVER: redis
      #REDIS_HOST: cache
      PORT: 5000

# Definición de los volúmenes para persistencia de datos
volumes:
  mariadb_datos:
