const datosReferidos = [
  {
    "documento_identidad_referido": "1001",
    "id_tipo_documento": 1,
    "nombre_referido": "Carlos Gómez",
    "correo_referido": "carlos.gomez@example.com",
    "telefono_referido": "3100000001",
    "empresa_referido": "Tech SA",
    "estado_referido": "pendiente",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-01-15T10:00:00Z",
    "fecha_primer_contacto": null,
    "fecha_conversion": null,
    "recompensa_generada": 0,
    "puntos_generados": 10,
    "documento_referente": "1",
    "creado_en": "2025-01-15T10:00:00Z",
    "actualizado_en": null,
    "observaciones": "Primer registro de prueba"
  },
  {
    "documento_identidad_referido": "1002",
    "id_tipo_documento": 1,
    "nombre_referido": "María López",
    "correo_referido": "maria.lopez@example.com",
    "telefono_referido": "3100000002",
    "empresa_referido": "Innova LTDA",
    "estado_referido": "contactado",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-02-10T11:00:00Z",
    "fecha_primer_contacto": "2025-02-12T14:00:00Z",
    "fecha_conversion": null,
    "recompensa_generada": 10000.0,
    "puntos_generados": 20,
    "documento_referente": "12",
    "creado_en": "2025-02-10T11:00:00Z",
    "actualizado_en": null,
    "observaciones": "Contactada para plan básico"
  },
  {
    "documento_identidad_referido": "1003",
    "id_tipo_documento": 1,
    "nombre_referido": "Andrés Ruiz",
    "correo_referido": "andres.ruiz@example.com",
    "telefono_referido": "3100000003",
    "empresa_referido": "VisionCorp",
    "estado_referido": "activo",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-03-05T09:30:00Z",
    "fecha_primer_contacto": "2025-03-07T10:00:00Z",
    "fecha_conversion": "2025-03-10T09:00:00Z",
    "recompensa_generada": 15000.0,
    "puntos_generados": 30,
    "documento_referente": "1",
    "creado_en": "2025-03-05T09:30:00Z",
    "actualizado_en": null,
    "observaciones": "Cliente activo"
  },
  {
    "documento_identidad_referido": "1004",
    "id_tipo_documento": 1,
    "nombre_referido": "Laura Torres",
    "correo_referido": "laura.torres@example.com",
    "telefono_referido": "3100000004",
    "empresa_referido": "Alpha SAS",
    "estado_referido": "pendiente",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-04-02T13:00:00Z",
    "fecha_primer_contacto": null,
    "fecha_conversion": null,
    "recompensa_generada": 0,
    "puntos_generados": 5,
    "documento_referente": "12",
    "creado_en": "2025-04-02T13:00:00Z",
    "actualizado_en": null,
    "observaciones": "Pendiente de contacto"
  },
  {
    "documento_identidad_referido": "1005",
    "id_tipo_documento": 1,
    "nombre_referido": "Felipe Martínez",
    "correo_referido": "felipe.martinez@example.com",
    "telefono_referido": "3100000005",
    "empresa_referido": "DataPlus",
    "estado_referido": "contactado",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-05-01T15:00:00Z",
    "fecha_primer_contacto": "2025-05-03T09:00:00Z",
    "fecha_conversion": null,
    "recompensa_generada": 5000.0,
    "puntos_generados": 15,
    "documento_referente": "1",
    "creado_en": "2025-05-01T15:00:00Z",
    "actualizado_en": null,
    "observaciones": "Esperando respuesta"
  },
  {
    "documento_identidad_referido": "1006",
    "id_tipo_documento": 1,
    "nombre_referido": "Paola Ríos",
    "correo_referido": "paola.rios@example.com",
    "telefono_referido": "3100000006",
    "empresa_referido": "NextGen",
    "estado_referido": "activo",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-06-20T08:00:00Z",
    "fecha_primer_contacto": "2025-06-22T12:00:00Z",
    "fecha_conversion": "2025-06-25T18:00:00Z",
    "recompensa_generada": 20000.0,
    "puntos_generados": 40,
    "documento_referente": "12",
    "creado_en": "2025-06-20T08:00:00Z",
    "actualizado_en": null,
    "observaciones": "Cliente fidelizado"
  },
  {
    "documento_identidad_referido": "1007",
    "id_tipo_documento": 1,
    "nombre_referido": "Jorge Pérez",
    "correo_referido": "jorge.perez@example.com",
    "telefono_referido": "3100000007",
    "empresa_referido": "ProTech",
    "estado_referido": "inactivo",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-07-10T10:00:00Z",
    "fecha_primer_contacto": "2025-07-12T11:00:00Z",
    "fecha_conversion": null,
    "recompensa_generada": 3000.0,
    "puntos_generados": 10,
    "documento_referente": "1",
    "creado_en": "2025-07-10T10:00:00Z",
    "actualizado_en": null,
    "observaciones": "Dejó de responder"
  },
  {
    "documento_identidad_referido": "1008",
    "id_tipo_documento": 1,
    "nombre_referido": "Sofía Herrera",
    "correo_referido": "sofia.herrera@example.com",
    "telefono_referido": "3100000008",
    "empresa_referido": "GreenCorp",
    "estado_referido": "activo",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-08-15T09:00:00Z",
    "fecha_primer_contacto": "2025-08-17T09:00:00Z",
    "fecha_conversion": "2025-08-20T09:00:00Z",
    "recompensa_generada": 18000.0,
    "puntos_generados": 35,
    "documento_referente": "12",
    "creado_en": "2025-08-15T09:00:00Z",
    "actualizado_en": null,
    "observaciones": "Convertida en cliente"
  },
  {
    "documento_identidad_referido": "1009",
    "id_tipo_documento": 1,
    "nombre_referido": "Camilo Díaz",
    "correo_referido": "camilo.diaz@example.com",
    "telefono_referido": "3100000009",
    "empresa_referido": "MegaNet",
    "estado_referido": "contactado",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-09-10T10:00:00Z",
    "fecha_primer_contacto": "2025-09-11T11:00:00Z",
    "fecha_conversion": null,
    "recompensa_generada": 7000.0,
    "puntos_generados": 20,
    "documento_referente": "1",
    "creado_en": "2025-09-10T10:00:00Z",
    "actualizado_en": null,
    "observaciones": "Pendiente de decisión"
  },
  {
    "documento_identidad_referido": "1010",
    "id_tipo_documento": 1,
    "nombre_referido": "Lucía Ramírez",
    "correo_referido": "lucia.ramirez@example.com",
    "telefono_referido": "3100000010",
    "empresa_referido": "NovaTech",
    "estado_referido": "pendiente",
    "id_plan_adquirido": 1,
    "fecha_referencia": "2025-10-05T14:00:00Z",
    "fecha_primer_contacto": null,
    "fecha_conversion": null,
    "recompensa_generada": 0,
    "puntos_generados": 5,
    "documento_referente": "12",
    "creado_en": "2025-10-05T14:00:00Z",
    "actualizado_en": null,
    "observaciones": "Nuevo registro para prueba"
  }
]
const bulkStoreReferidos = async (db)=>{
    try {
        await db.refered.bulkCreate(datosReferidos);
        return "Datos de referidos insertados correctamente.";
    } catch (error) {
        console.error("Error al insertar datos de referidos:", error);
        return "Error al insertar datos de referidos.";
    }
}
export default bulkStoreReferidos;